# Generated by Django 4.2.5 on 2023-09-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='summary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
